name: Yarn and Lint CI
on: 
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      # - name: Add ESLint
      #   run: yarn global add eslint
      # - name: Run ESLint
      #   run: eslint ./ --ext=".js,.jsx,.ts,.tsx"
      - name: build
        run: yarn build
